//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookForRide.BikeData.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookForRideLog
    {
        public int Id { get; set; }
        public string LogName { get; set; }
        public string LogDescription { get; set; }
        public string LogTime { get; set; }
        public string LogType { get; set; }
    }
}
